import { Router } from "express";
import { healthRouter } from "./health.routes.js";
import { authRouter } from "./auth.routes.js";
import { sitesRouter } from "./sites.routes.js";
import { workersRouter } from "./workers.routes.js";
import { activitiesRouter } from "./activities.routes.js";
import { usersRouter } from "./users.routes.js";
import { pointagesRouter } from "./pointages.routes.js";
import { paymentsRouter } from "./payments.routes.js";
import { dashboardRouter } from "./dashboard.routes.js";
import { auditRouter } from "./audit.routes.js";
import { reportsRouter } from "./reports.routes.js";
import { biometricRouter } from "./biometric.routes.js";
import { zonesRouter } from "./zones.routes.js";
import { parcelsRouter } from "./parcels.routes.js";
import { teamsRouter } from "./teams.routes.js";

export const apiRouter = Router();

apiRouter.use(healthRouter);
apiRouter.use(authRouter);
apiRouter.use(sitesRouter);
apiRouter.use(activitiesRouter);
apiRouter.use(workersRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use(pointagesRouter);
apiRouter.use(paymentsRouter);
apiRouter.use(dashboardRouter);
apiRouter.use(auditRouter);
apiRouter.use(reportsRouter);
apiRouter.use(biometricRouter);
apiRouter.use(zonesRouter);
apiRouter.use(parcelsRouter);
apiRouter.use(teamsRouter);
