import { Router } from "express";
import { healthRouter } from "./health.routes.js";
import { authRouter } from "./auth.routes.js";
import { sitesRouter } from "./sites.routes.js";
import { workersRouter } from "./workers.routes.js";
import { activitiesRouter } from "./activities.routes.js";
import { usersRouter } from "./users.routes.js";
import { pointagesRouter } from "./pointages.routes.js";
import { paymentsRouter } from "./payments.routes.js";
import { dashboardRouter } from "./dashboard.routes.js";
import { auditRouter } from "./audit.routes.js";
import { reportsRouter } from "./reports.routes.js";
import { biometricRouter } from "./biometric.routes.js";
import { biometricTemplatesRouter } from "./biometric-templates.routes.js";
import { zonesRouter } from "./zones.routes.js";
import { parcelsRouter } from "./parcels.routes.js";
import { teamsRouter } from "./teams.routes.js";
import { presenceRouter } from "./presence.routes.js";
import { badgesRouter } from "./badges.routes.js";
import { workflowsRouter } from "./workflows.routes.js";
import { dailyReportsRouter } from "./daily-reports.routes.js";
import { appSettingsRouter } from "./app-settings.routes.js";
import { systemRouter } from "./system.routes.js";

export const apiRouter = Router();

apiRouter.use(healthRouter);
apiRouter.use(authRouter);
apiRouter.use(appSettingsRouter);
apiRouter.use(systemRouter);
apiRouter.use(sitesRouter);
apiRouter.use(activitiesRouter);
apiRouter.use(workersRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use(pointagesRouter);
apiRouter.use(paymentsRouter);
apiRouter.use(dashboardRouter);
apiRouter.use(auditRouter);
apiRouter.use(reportsRouter);
apiRouter.use(biometricRouter);
apiRouter.use(biometricTemplatesRouter);
apiRouter.use(zonesRouter);
apiRouter.use(parcelsRouter);
apiRouter.use(teamsRouter);
apiRouter.use(presenceRouter);
apiRouter.use(badgesRouter);
apiRouter.use(workflowsRouter);
apiRouter.use(dailyReportsRouter);
